import {
  Drumstick,
  Dumbbell,
  Palette,
  Scissors,
  SprayCan,
  BookOpen,
  Home,
  Flower2,
  Car,
  Trees,
  type LucideIcon,
} from "lucide-react";

export type Service = {
  id: string;
  title: string;
  categorySlug: string;
  categoryLabel: string;
  price: number;
  priceUnit: string;
  sellerName: string;
  sellerInitials: string;
  description: string;
  icon: LucideIcon;
};

export const services: Service[] = [
  {
    id: "1",
    title: "Fried Chicken Plates",
    categorySlug: "food",
    categoryLabel: "Food",
    price: 55,
    priceUnit: "per order",
    sellerName: "Marcus T.",
    sellerInitials: "MT",
    description: "Homemade fried chicken plates with sides, made to order.",
    icon: Drumstick,
  },
  {
    id: "2",
    title: "Personal Training Session",
    categorySlug: "beauty",
    categoryLabel: "Fitness",
    price: 20,
    priceUnit: "per hour",
    sellerName: "Jordan P.",
    sellerInitials: "JP",
    description: "1-on-1 strength training sessions at McComas.",
    icon: Dumbbell,
  },
  {
    id: "3",
    title: "Makeup & Nails",
    categorySlug: "beauty",
    categoryLabel: "Beauty",
    price: 80,
    priceUnit: "per session",
    sellerName: "Ava R.",
    sellerInitials: "AR",
    description: "Full glam makeup and gel nails for events.",
    icon: Palette,
  },
  {
    id: "4",
    title: "Fresh Fade Haircuts",
    categorySlug: "haircut",
    categoryLabel: "Haircut",
    price: 15,
    priceUnit: "per cut",
    sellerName: "Devon L.",
    sellerInitials: "DL",
    description: "Clean fades and line-ups, walk-ins welcome near Hethwood.",
    icon: Scissors,
  },
  {
    id: "5",
    title: "Apartment Deep Clean",
    categorySlug: "cleaning",
    categoryLabel: "Cleaning",
    price: 40,
    priceUnit: "per visit",
    sellerName: "Priya S.",
    sellerInitials: "PS",
    description: "Full apartment cleaning, move-out ready in under 3 hours.",
    icon: SprayCan,
  },
  {
    id: "6",
    title: "CS 2114 Textbook Bundle",
    categorySlug: "textbooks",
    categoryLabel: "Textbooks",
    price: 35,
    priceUnit: "flat rate",
    sellerName: "Ethan W.",
    sellerInitials: "EW",
    description: "Barely used bundle, includes lab manual and notes.",
    icon: BookOpen,
  },
  {
    id: "7",
    title: "Sublease Near Union",
    categorySlug: "subleasing",
    categoryLabel: "Subleasing",
    price: 650,
    priceUnit: "per month",
    sellerName: "Grace K.",
    sellerInitials: "GK",
    description: "1BR sublease available for spring semester, pet friendly.",
    icon: Home,
  },
  {
    id: "8",
    title: "Custom Bouquets",
    categorySlug: "flowers",
    categoryLabel: "Flowers",
    price: 25,
    priceUnit: "per bouquet",
    sellerName: "Lily N.",
    sellerInitials: "LN",
    description: "Fresh seasonal bouquets, same-day delivery on campus.",
    icon: Flower2,
  },
  {
    id: "9",
    title: "Lawn Mowing & Yard Work",
    categorySlug: "landscaping",
    categoryLabel: "Landscaping",
    price: 30,
    priceUnit: "per yard",
    sellerName: "Sam B.",
    sellerInitials: "SB",
    description: "Weekly mowing and trimming for off-campus houses.",
    icon: Trees,
  },
  {
    id: "10",
    title: "Airport & Store Runs",
    categorySlug: "shopping",
    categoryLabel: "Shopping",
    price: 18,
    priceUnit: "per trip",
    sellerName: "Noah F.",
    sellerInitials: "NF",
    description: "Rides to ROA airport, Kroger, and Target runs on request.",
    icon: Car,
  },
];
